ChildProject/ChildProject.py
=> optional columns

.gitignore, .travis.yml, ChildProject/ChildProject.py, docs/FORMATTING_TEMPLATE.md, docs/_config.yml, docs/generate_docs.py, requirements.txt, tests/test_convert.py, tests/test_import.py
=> Data validation refactoring

ChildProject/ChildProject.py, convert.py, docs/README.md
Closes #25.
Usage:
1. create `convert.sh`
```bash
#!/bin/bash
python convert.py --source ../data/namibia/ --name mp --format WAV --codec pcm_s16le --sampling 16000 --threads 4
```
2. run `$ chmod +x convert.sh`
3. run `$ sbatch --mem=64G --time=5:00:00 --cpus-per-task=4 --ntasks=1 -o namibia.txt ./convert.sh`
=> Multithread conversion

ChildProject/annotations.py
It is significantly faster this way... but what about thread-safety ?
=> multithread annotation importation

docs/README.md, import_annotations.py
=> allow to import one annotation at a time using the script

ChildProject/annotations.py
=> consistency checks before importing annotations

docs/templates/PROJECTS.md
=> datalad documentation

ChildProject/cmdline.py, setup.py
This should increase compatiblity with other systems
=> setup executable with console_scripts instead of scripts

ChildProject/annotations.py, ChildProject/projects.py, ChildProject/tables.py, ChildProject/utils.py, docs/templates/FORMATTING.md, examples/invalid_raw_data/metadata/recordings.csv, examples/valid_raw_data/metadata/recordings.csv, tests/test_validation.py
- add function option for table columns
- noisy_setting
- might_feature_gaps
- start_time_accuracy
=> data quality flags

ChildProject/pipelines/zooniverse.py, docs/ZOONIVERSE.md
=> Zooniverse retrieve-classifications

ChildProject/annotations.py, ChildProject/cmdline.py, docs/TOOLS.md, tests/test_annotations.py
=> child-project rename-annotations

ChildProject/annotations.py, ChildProject/cmdline.py, docs/TOOLS.md
=> Annotations multithread validation (fixes #116)

ChildProject/projects.py, ChildProject/tables.py, docs/templates/FORMATTING.md, tests/test_validation.py
=> Remove excel support

ChildProject/annotations.py, tests/test_annotations.py
Allow users to use a custom callable to convert any kind of annotation to our format.
#131
=> custom annotation function support (fixes #131)

docs/generate_docs.py, docs/templates/TOOLS.md, docs/templates/ZOONIVERSE.md
=> auto-generated cli docs (fixes #99)

ChildProject/annotations.py, tests/test_annotations.py
=> its importation fixes and tests (fixes #137)

ChildProject/pipelines/zooniverse.py, tests/test_zooniverse.py
allows users to set chunks length, min. amount of chunks, or to disable chunk splitting
=> zooniverse: custom chunk splitting

ChildProject/pipelines/__init__.py, ChildProject/pipelines/sampler.py, ChildProject/pipelines/samplers.py, ChildProject/pipelines/zooniverse.py, docs/source/ChildProject.pipelines.rst, docs/source/samplers.rst, docs/source/tools.rst, requirements.txt, setup.py
=> sampler output standardization

ChildProject/annotations.py, tests/test_annotations.py, tests/truth/eaf.csv, tests/truth/eaf_solis.csv, tests/truth/intersect_a.csv, tests/truth/intersect_b.csv, tests/truth/textgrid.csv
=> make annotation_filename relative to annotations/<set>/converted

ChildProject/pipelines/samplers.py, ChildProject/pipelines/zooniverse.py
=> zooniverse pipeline improvements and fixes

docs/source/examples.rst, docs/source/index.rst, docs/source/tools.rst, examples/import_vtc.py, examples/zooniverse.py
Alex suggests we provide more examples of python scripts using the package. Ideas are welcome !
- what more ?
=> More examples

ChildProject/tables.py
=> Annotation validation optimization

ChildProject/annotations.py
=> merge annotations fix for empty annotations

ChildProject/annotations.py
=> vcm conversion

ChildProject/pipelines/samplers.py
=> vtc compatible high-volubility sampler

ChildProject/cmdline.py, ChildProject/projects.py, docs/source/tools.rst
=> dataset overview

ChildProject/pipelines/zooniverse.py
=> more resilient zooniverse uploads

ChildProject/annotations.py
=> Improving error messages during importation/validation

docs/source/annotations.rst, docs/source/format.rst, docs/source/install.rst, docs/source/metrics.rst
The documentation of the annotation system desperately needs improvements.
I think visual explanations would be helpful.
Ideas welcome!
=> more explanatory documentation of the annotation system

CHANGELOG.md, ChildProject/annotations.py, ChildProject/metrics.py, ChildProject/pipelines/eafbuilder.py, docs/source/api-annotations.rst, requirements.txt, tests/data/time_range_annotations.csv, tests/data/time_range_recordings.csv, tests/test_annotations.py, tests/truth/time_range.csv
=> get annotations within a certain time range

CHANGELOG.md, ChildProject/pipelines/metrics.py, ChildProject/pipelines/pipeline.py, ChildProject/pipelines/processors.py, ChildProject/pipelines/samplers.py, ChildProject/projects.py, docs/source/processors.rst, tests/test_convert.py, tests/test_samplers.py
Introducing a new option to process only specific recordings.
=> --recordings option for all audio processors

ChildProject/annotations.py, ChildProject/cmdline.py, ChildProject/projects.py, docs/source/tools.rst, tests/test_annotations.py, tests/test_validation.py
=> validate custom recording profiles or annotation sets

ChildProject/cmdline.py, ChildProject/projects.py, docs/source/_ext/directives.py, docs/source/format.rst, examples/valid_raw_data/docs/children.csv, tests/test_cli.py, tests/test_documentation.py, tests/truth/docs.csv
=> Documenting the metadata

.gitignore, CHANGELOG.md, ChildProject/pipelines/samplers.py, docs/source/samplers.rst, tests/test_samplers.py
=> Conversation sampler

CHANGELOG.md, ChildProject/annotations.py, tests/test_annotations.py
=> get_within_ranges() function

ChildProject/annotations.py, ChildProject/converters.py
=> Adding a msc_type tier

ChildProject/pipelines/zooniverse.py, docs/source/zooniverse.rst, requirements.txt, tests/test_zooniverse.py
Option in the zooniverse extract-chunks pipeline to have a spectrogram outputted as an image alongside the audio clips
=> Zoo spectrogram

.github/workflows/publish.yml, CHANGELOG.md, ChildProject/projects.py, tests/test_projects.py, tests/truth/ages.csv
=> compute age format arguments

CHANGELOG.md, ChildProject/pipelines/eafbuilder.py
Implementing the verification that speaker_id exists and is not null before using it to name the tier. 
```python
if "speaker_id" in segment and not pd.isnull(segment["speaker_id"]):
```
=> solving the issue speaker_id NA #438

CHANGELOG.md, ChildProject/projects.py, examples/invalid_raw_data/metadata/recordings.csv, examples/invalid_raw_data/recordings/raw/test_1_is_broken.mp3, tests/test_validation.py
Here's the update: 
- verification added to include symlink cases
- test function modified
- example cases added to the indalid_dataset
=> Projects.py/broken symlinks validate

CHANGELOG.md, ChildProject/projects.py
have a warning when not able to read sample rate rather than code failure
=> validation no sample rate warning

CHANGELOG.md, ChildProject/pipelines/eafbuilder.py, tests/test_eaf.py
fix a bug where the eaf builder replicates 2 times the subtree structure
=> Eaf builder/subtree

CHANGELOG.md, ChildProject/cmdline.py
Adding an init command to initiate a new Childproject project, with correct structure and files (empty) to begin with
=> add init command
